services:
  insider-guide-back:
    build: .
    container_name: insider-guide-back
    restart: unless-stopped
    ports:
      - "3013:80"
    networks:
      - web

networks:
  web:
    external: true
