// ctaPages.js — read a DM-only CTA page (/g/<slug>) from the content library.
//
// Plain `fetch` to PostgREST, NOT a second supabase-js client: this repo pins
// @supabase/supabase-js into its own vendor chunk (vite.config.js) and a second
// GoTrue/realtime instance for one anonymous read is dead weight on a public
// page (CLAUDE.md rule 3). Same shape as scripts/build-seo.mjs, browser-side.
//
// The URL and key below are the content library's PUBLIC anon credentials for a
// different Supabase project — the same exposure class as VITE_SUPABASE_ANON_KEY,
// and deliberately shipped in the bundle: RLS plus a published-only RPC are what
// protect the data, the key grants nothing by itself. Baking defaults means a new
// page needs zero ops; VITE_CONTENTKO_SUPABASE_URL / VITE_CONTENTKO_ANON_KEY
// override both when set. NEVER put a service-role key here.

const DEFAULT_URL = 'https://dnehqsalmcbimrdtlpsg.supabase.co'
const DEFAULT_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuZWhxc2FsbWNiaW1yZHRscHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NTIwNTMsImV4cCI6MjA4OTQyODA1M30.cGRdmaaOh_A0WU9BHDJAhNQ8uoBgLn4MEM1DiQPpgNs'

export const CONTENTKO_URL = (import.meta.env.VITE_CONTENTKO_SUPABASE_URL || DEFAULT_URL).replace(/\/$/, '')
export const CONTENTKO_ANON_KEY = import.meta.env.VITE_CONTENTKO_ANON_KEY || DEFAULT_ANON_KEY

/** Site identifier this bundle is registered under in the content library. */
export const CTA_SITE = 'insider-guide'

export const CTA_KINDS = ['guide', 'tips', 'link']
export const CTA_LANGS = ['en', 'es', 'it', 'pt', 'ru']

// Slugs are generated by the library's slugifier; anything outside this shape
// is garbage pasted into the URL bar and not worth a round-trip. (Slugs ending
// in .json/.xml/.txt/.map never reach the SPA — nginx 404s those extensions.)
const SLUG_RE = /^[a-z0-9](?:[a-z0-9._-]{0,118}[a-z0-9])?$/i

const FETCH_TIMEOUT_MS = 8000
const CACHE_TTL_MS = 5 * 60 * 1000

/** Transport failure (network, timeout, 5xx). Distinct from "no such page". */
export class CtaFetchError extends Error {
  constructor(message, { status } = {}) {
    super(message)
    this.name = 'CtaFetchError'
    this.status = status ?? null
  }
}

function headers() {
  return {
    apikey: CONTENTKO_ANON_KEY,
    Authorization: `Bearer ${CONTENTKO_ANON_KEY}`,
    'Content-Type': 'application/json',
  }
}

export function isValidCtaSlug(slug) {
  return typeof slug === 'string' && SLUG_RE.test(slug)
}

const str = (v) => (typeof v === 'string' && v.trim() ? v.trim() : null)

// Only http(s) or a site-relative path may become the CTA href — a row can
// never inject `javascript:` or `data:` into an anchor.
function safeUrl(v) {
  const s = str(v)
  if (!s) return null
  if (s.startsWith('/') && !s.startsWith('//')) return s
  try {
    const u = new URL(s)
    return u.protocol === 'https:' || u.protocol === 'http:' ? u.href : null
  } catch {
    return null
  }
}

function normalizeSection(raw) {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null
  const heading = str(raw.heading)
  const body = str(raw.body)
  const bullets = Array.isArray(raw.bullets) ? raw.bullets.map(str).filter(Boolean) : []
  if (!heading && !body && bullets.length === 0) return null
  return { heading, body, bullets }
}

/**
 * Defensive row → page validator. Drops anything unrenderable rather than
 * trusting a remote shape; returns null when the row cannot be a page.
 */
export function normalizeCtaPage(row) {
  if (!row || typeof row !== 'object') return null
  const slug = str(row.slug)
  const title = str(row.title)
  if (!slug || !title) return null

  const kind = CTA_KINDS.includes(row.kind) ? row.kind : 'guide'
  const lang = CTA_LANGS.includes(row.lang) ? row.lang : 'en'
  const sections = Array.isArray(row.sections) ? row.sections.map(normalizeSection).filter(Boolean) : []
  const ctaUrl = safeUrl(row.cta_url)
  const publishedAt = str(row.published_at)
  const publishedDate = publishedAt ? new Date(publishedAt) : null

  return {
    slug,
    site: str(row.site) || CTA_SITE,
    kind,
    lang,
    title,
    hero: str(row.hero),
    sections,
    ctaLabel: ctaUrl ? str(row.cta_label) : null,
    ctaUrl,
    publishedAt: publishedDate && !Number.isNaN(publishedDate.getTime()) ? publishedDate : null,
  }
}

// Tiny in-module cache so back/forward navigation within one session does not
// re-fetch (PostgREST answers no-cache). Caches misses too — a typo'd DM link
// hammered by a scraper should not fan out to the library.
const cache = new Map()

function cached(slug) {
  const hit = cache.get(slug)
  if (!hit) return undefined
  if (Date.now() - hit.at > CACHE_TTL_MS) {
    cache.delete(slug)
    return undefined
  }
  return hit.page
}

/**
 * Resolve a published page for this site. Returns the normalized page, or
 * `null` when the library has no published page at that slug. Throws
 * CtaFetchError on transport failure so the caller can tell "not found" from
 * "library unreachable" and render each honestly.
 */
export async function fetchCtaPage(slug, { signal } = {}) {
  if (!isValidCtaSlug(slug)) return null
  const hit = cached(slug)
  if (hit !== undefined) return hit

  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS)
  const onOuterAbort = () => controller.abort()
  signal?.addEventListener('abort', onOuterAbort, { once: true })

  let res
  try {
    res = await fetch(`${CONTENTKO_URL}/rest/v1/rpc/cta_page_by_slug`, {
      method: 'POST',
      headers: headers(),
      body: JSON.stringify({ p_site: CTA_SITE, p_slug: slug }),
      signal: controller.signal,
    })
  } catch (err) {
    if (signal?.aborted) throw err
    throw new CtaFetchError(err?.name === 'AbortError' ? 'Timed out' : err?.message || 'Network error')
  } finally {
    clearTimeout(timer)
    signal?.removeEventListener('abort', onOuterAbort)
  }

  if (!res.ok) {
    throw new CtaFetchError(`HTTP ${res.status}`, { status: res.status })
  }

  let rows
  try {
    rows = await res.json()
  } catch {
    throw new CtaFetchError('Malformed response')
  }

  const page = normalizeCtaPage(Array.isArray(rows) ? rows[0] : null)
  cache.set(slug, { at: Date.now(), page })
  return page
}

/**
 * Count one page view. Fire-and-forget: never awaited by the page, never
 * blocks rendering, swallows every failure. `keepalive` lets the beacon
 * survive the visitor tapping the CTA straight away.
 */
export function recordCtaHit(slug) {
  if (!isValidCtaSlug(slug)) return
  try {
    fetch(`${CONTENTKO_URL}/rest/v1/rpc/cta_page_hit`, {
      method: 'POST',
      headers: headers(),
      body: JSON.stringify({ p_site: CTA_SITE, p_slug: slug }),
      keepalive: true,
    }).catch(() => {})
  } catch {
    /* ignore — analytics must never surface to the visitor */
  }
}
